apiVersion: v1
kind: Service
metadata:
  name: rssavni-service
  namespace: default
spec:
  selector:
    app: rssavni
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
